/// if future completes it will be handled by [then] method
/// if future returns error event loop sends that error to [catchError]
/// also there is [onError] method which has more priority then [catchError]

void main() {}
